# Site settings
title: David Meagher
email: meagherjdavid@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://davidmeagher.net" # the base hostname & protocol for your site
github_username: DavidMeagher1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Syntax highlighting
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false

# Theme settings
minima:
  skin: dark

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Date format
date_format: "%B %d, %Y"
